Completed task on fp
S1IverFox/study pull request #2
Opened 2021-04-20 14:38 UTC by S1IverFox

2021-04-23 14:18 UTC, nut4k1 requested changes

2021-04-23 14:18 UTC, nut4k1 commented on test/exercise/fp/solution.rb
> +        filtered_array = array.select { |film| film['country'].to_s.split(',').length >= 2 && film['rating_kinopoisk'].to_f.positive? }
need to check for cases, when _country_ or _rating_kinopoisk_ is nil

2021-04-23 14:18 UTC, nut4k1 commented on test/exercise/fp/solution.rb
> +        filtered_array.map { |film| film['rating_kinopoisk'].to_f }.reduce(:+) / filtered_array.length
wow. you can simply use `sum`
p.s.: it's not okay to apply math or anything after a block of code
```
a = blabla.map {}
a / f
```
is better than `blabla.map {} / msh`

2021-04-23 14:18 UTC, nut4k1 commented on test/exercise/fp/solution.rb
> +        filtered_array.reduce(0) { |sum, film| sum + film['name'].count('и') }
need a safe navigation

2021-04-23 14:18 UTC, nut4k1 commented on test/exercise/fp/solution.rb
> +        filtered_array = films.select { |film| film['rating_kinopoisk'].to_f >= threshold }
need a safe navigation

2021-04-23 15:35 UTC, S1IverFox commented on test/exercise/fp/solution.rb
> +        filtered_array = array.select { |film| film['country'].to_s.split(',').length >= 2 && film['rating_kinopoisk'].to_f.positive? }
Но разве проверка на то, что их значения положительные, не подразумевает, что они не могут быть nil?

2021-04-23 15:58 UTC, S1IverFox commented on test/exercise/fp/solution.rb
> +        filtered_array = array.select { |film| film['country'].to_s.split(',').length >= 2 && film['rating_kinopoisk'].to_f.positive? }
> need to check for cases, when _country_ or _rating_kinopoisk_ is nil

Но разве проверка на то, что их значения положительные, не подразумевает, что они не могут быть nil?

2021-04-23 16:02 UTC, S1IverFox commented on test/exercise/fp/solution.rb
> +        filtered_array.map { |film| film['rating_kinopoisk'].to_f }.reduce(:+) / filtered_array.length
Можно и sum, конечно, но в условии сказано, что надо использовать map и reduce.

2021-04-29 08:55 UTC, Andrew8xx8 approved these changes

2021-05-01 06:23 UTC, merged